name: SFDX-CLI Deploy from repository
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git hub Code
        uses: actions/checkout@v3
      - name: Install SFDX
        run: |
             npm install @salesforce/cli --global
             sf --version
